### ISSUE TITLE
[FeatureRequest]
Additional temperature Sensors

### ISSUE THREAD

**Issue by cloudbr34k84** [wilsto/pool-monitor-card#1]
I have 2 pool thermometers.  One that measures the bottom and one that measure the top. It would be good to have multiple sensors supported in the one card. I can just have 2 cards but it would be good to just have one.

**Comment by wilsto** [comment]
I'm concerned that this would make the card configuration too complex for an exceptional case, now I'm leaving the request open and if others have the same need or if another development allows me to include it without complicating it, I'll consider it. Is it ok for you ?

**Comment by cloudbr34k84** [comment]
Yeah man totally understand! I use my average sensor most of the time.  
You can probably close it. I highly doubt anyone else has 2 pool thermometers lol

**Comment by wilsto** [comment]
Hi @cloudbr34k84 you're not alone to have custom entities , i will work on it this week end

**Comment by wilsto** [comment]
Done in 1.4
https://github.com/wilsto/pool-monitor-card#temperature
![image](https://github.com/wilsto/pool-monitor-card/assets/4889715/91f21f3c-1042-42b2-81db-0a6d1dc436e0)

**Comment by cloudbr34k84** [comment]
Awesome, love it! can you have as many as you like or is it just 2?

**Comment by wilsto** [comment]
just 2. how many do you have ?

**Comment by cloudbr34k84** [comment]
> just 2. how many do you have ? 

I have 4 parts of my pool I can read the temp.  
Zodiac System measures the water in the pipes 
My pool heater measures the outlet pipe 
And the 2 devices I have in the pool lol 

It's fine ill just have 2 separates cards, you have done heaps!

**Comment by K4BlOs** [comment]
Hello, would it be possible to have 4 temperature sensors? 
1. pool in (from heating)
2. pool out (to heating)
4. pool temp
5. air temp
