### ISSUE TITLE
[FeatureRequest] Reorder the sensors

### ISSUE THREAD

**Issue by wilsto** [wilsto/pool-monitor-card#11]
Is there a way to reorder the sensors? I assumed it was based on the order in which they were laid out in the config but it appears to be a fixed order.

from https://community.home-assistant.io/t/lovelace-card-pool-monitoring-card-pool-temperature-ph-orp-and-tds/572179/27?u=wilsto

**Comment by TheRealFalseReality** [comment]
I second this!

**Comment by Intecpsp** [comment]
I third this!

**Comment by wilsto** [comment]
@TheRealFalseReality @Intecpsp Done in the latest Version 2.0.

![image](https://github.com/user-attachments/assets/ad48a9ae-fe51-4f46-b14f-91b7d89db724)
