### ISSUE TITLE
[FeatureRequest] add last updated time of sensor

### ISSUE THREAD

**Issue by wilsto** [wilsto/pool-monitor-card#13]
is it possible to add somewhere the last time the sensor was updated as then makes it an easy glance when checking parameters incase a sensor has frozen it’s readings for whatever reason

from https://www.facebook.com/groups/HomeAssistant/posts/3509729799298365/?comment_id=3512878688983476

**Comment by wilsto** [comment]
Done in compact = false in v1.5
![image](https://github.com/wilsto/pool-monitor-card/assets/4889715/f9532e4c-52ce-4d00-af12-9abd44939600)

**Comment by Millhouse1981** [comment]
The Last Update from Sensor are not showing.
