### ISSUE TITLE
add last updated time of sensor #13

### ISSUE THREAD

**Issue by Millhouse1981** [wilsto/pool-monitor-card#15]
- Latest version V.1.5
- pool_monitor_card.js

Probably contains the old version of V.1.4
It is not displayed when the sensors were last updated
This entry is also in the Pool_Monitor_card.js: const CARD_VERSION = '1.4.0';

![Screenshot 2023-07-18 134023](https://github.com/wilsto/pool-monitor-card/assets/127554324/5474f3b0-ac13-42b5-b2a5-c34c5618777d)

**Comment by wilsto** [comment]
corrected in 1.5.1
