### ISSUE TITLE
[FeatureRequest] Blueriiot information

### ISSUE THREAD

**Issue by DAVIZINH0** [wilsto/pool-monitor-card#16]
Hello.
I dont know where to put this information.
I have the 2 bluerioot sensors because I had a clore pool and change this week to a salinity pool.

The blue connect go measure this 3 values:
- Temperature
- PH
- ORP (mv) 

The blue connect plus with gold sensor, measure this 4 values:
- Temperature
- PH
- ORP (mv)
- Salinity (g/L)

i hope this information will be usefull to update the readme page :-)

**Comment by wilsto** [comment]
Thanks :) added to the readme
