### ISSUE TITLE
[FeatureRequest] add g/L as salinity_unit option

### ISSUE THREAD

**Issue by DAVIZINH0** [wilsto/pool-monitor-card#17]
Hello,

The bluerriot blue conect gold, measure the salinity of a salt pool, and the blueriiot2mqtt report this value in g/L not mg/L

Can you add the g/L as salinity_unit option??

thanks

**Comment by wilsto** [comment]
Hello @DAVIZINH0 ,
you can already do this with this setting : 

```
salinity: sensor.your_salinity_entity
salinity_unit: g/L
salinity_setpoint: 4.5
salinity_step: 0.5
```

![image](https://github.com/wilsto/pool-monitor-card/assets/4889715/95bd9c7a-c34b-415c-9525-c63acfbcbc9b)

**Comment by DAVIZINH0** [comment]
im stupid!. i try this but i not use salinity setpoint, i used tds_setpoint because previously i try with tds. 
Its may fault. sorry.

only one posible improvement. If i put 3 at salinity_setpoint, and 0.5 as salinity_step. The graphical its confuse because not show the decimals bewteen colours (you can try to see the problem.

thanks a lot man! this card is great!!!

**Comment by wilsto** [comment]
Thanks @DAVIZINH0 , the decimal display should be corrected.
