### ISSUE TITLE
[FeatureRequest] : Salinity Level

### ISSUE THREAD

**Issue by cloudbr34k84** [wilsto/pool-monitor-card#2]
I have a pool sensors that support salt levels. Can we get another sensor type added pls?

**Comment by wilsto** [comment]
Hi @cloudbr34k84, can you give me information about your sensor so I can see how to implement your request ?

**Comment by cloudbr34k84** [comment]
Hey yeah sorry i should have explained more. I have a magnesium pool - https://www.magnapool.com/
With the Device, I have I'm able to measure the salt levels in the pool. salinity levels should be between 4000–4500 ppm

Is that what you need??

**Comment by wilsto** [comment]
I add salinity sensor in version 1.4 (you will have to change the setpoint to have the one you want)
https://github.com/wilsto/pool-monitor-card#salinity
