### ISSUE TITLE
[FeatureRequest] Add water level sensor

### ISSUE THREAD

**Issue by hessbe** [wilsto/pool-monitor-card#20]
**Is your feature request related to a problem? Please describe.**
I have a water level / height sensor and the pool regulates water intake itself. There is currently no possibility to display the current value

**Describe the solution you'd like**
Add a sensor like temperatur or ph to display a water level.

**Additional context**
The height is in cm. The controller refills the pool if it gets too low or pumps water out if its too full (due to rain). 
Defined levels:
47 cm: too low, shut down pump (pump could run dry), should never be hit
49 cm: start refilling until 51cm
51 cm: level ok, turn off filling
54 cm: high level, pump water out by reverse direction through sand filter

So if it is possible be able to define those limits

**Comment by alexdelprete** [comment]
Hi @hessbe, can you share what sensor are you using to detect water level? Is it reliable?

Thanks.

**Comment by hessbe** [comment]
@alexdelprete  I actually don't know as it isn't a DIY solution. As far as I know it is a pressure sensor which is working reliably.

It is a Aseko Home Chlorine dosing system (https://www.asekopool.com/en/asin-aqua-home-en/) which reads the sensor and controls the pump / refill valve.

You can read the manual of the dosing system here: https://files.aseko.com/index.php/s/Documentation-manuals/download?path=%2FASIN%20AQUA%20Home%2FManual-2024&files=AA-Home_OXY-VS-Man-EN-2024-01.pdf&downloadStartSecret=9hrbpmdhx5q

There is a picture of the sensor at the beginning as spare part and a description how it is working (pressure)

**Comment by alexdelprete** [comment]
Thanks. Very nice system.

**Comment by wilsto** [comment]
Very nice DIY @hessbe , I will add this new requirement.

**Comment by wilsto** [comment]
Done in v1.8.0 👍
