### ISSUE TITLE
[FeatureRequest] Multiple measurement types

### ISSUE THREAD

**Issue by PandCall** [wilsto/pool-monitor-card#21]
To complete your development and open it up to as many pool types as possible.
The following measures should be added.

DebitMetre, L/m (or other, depending on the units used in different countries)
UV radiation, nm (I personally use UV treatment)
Volume of product in cans, L (or other, depending on the units used in different countries) (pH+, pH-, etc...)
Weight of product cans, Kg (or other depending on the unit used in the country).

Very good work 
Regards

**Comment by wilsto** [comment]
thanks @PandCall , ok for this implementation

**Comment by wilsto** [comment]
Done in v1.8.0 👍

**Comment by PandCall** [comment]
Cool, I try ASAP
Regards
