### ISSUE TITLE
[FeatureRequest] temperature_2_name missing in documentation

### ISSUE THREAD

**Issue by ahuffman** [wilsto/pool-monitor-card#24]
**Is your feature request related to a problem? Please describe.**
Way to add a label for `temperature_2`, such as a `temperature_name_2` setting.

**Describe the solution you'd like**
Ability to label the second temperature monitor.

**Describe alternatives you've considered**
n/a

**Additional context**
I have 2 temperature sensors from my Hayward Omnilogic pool controller, one for air temp and second for water temp.

**Comment by ahuffman** [comment]
Nevermind, I found that the setting is `temperature_2_name` after experimenting.  Missing in documentation.

**Comment by wilsto** [comment]
I've improved the documentation. Thanks
