### ISSUE TITLE
Add portuguese language

### ISSUE THREAD

**Issue by jorgemiguel4** [wilsto/pool-monitor-card#27]
Hi, can you add portuguese language?

To help you a bit I did the translation for you, it's only needed to add to the code.

Thank you

'pt': {
    "state": {
      "1": "Muito Baixo",
      "2": "Aceitável Baixo",
      "3": "Ideal",
      "4": "Ideal",
      "5": "Aceitável Alto",
      "6": "Muito Alto"
    },
    "sensor": {
      "temperature": "Temperatura",
      "temperature_2": "Temperatura 2",
      "ph": "pH",
      "orp": "ORP",
      "tds": "TDS",
      "salinity": "Salinidade",
      "cya": "Ácido Cianúrico",
      "calcium": "Cálcio",
      "phosphate": "Fosfato",
      "alkalinity": "Alcalinidade",
      "free_chlorine": "Cloro Livre",
      "total_chlorine": "Cloro Total",
      "pressure": "Pressão"
    },
    "time": {
      "seconds": "agora mesmo",
      "minutes": "há {minutes} minuto{plural}",
      "hours": "há {hours} hora{plural}",
      "days": "há {days} dia{plural}"
    }
  }

**Comment by MrSnakeSPb** [comment]
Thank you for your cool integration, please add a translation into Russian:
  'ru': {
    "state": {
      "1": "Слишком низкий",
      "2": "Приемлемо низкий",
      "3": "Идеальный",
      "4": "Идеальный вариант",
      "5": "Приемлемо высокий",
      "6": "Слишком высокий"
    },
    "sensor": {
      "temperature": "Температура",
      "temperature_2": "Температура 2",
      "ph": "pH",
      "orp": "ORP",
      "tds": "TDS",
      "salinity": "Соленость",
      "cya": "Циануровая кислота",
      "calcium": "Кальций",
      "phosphate": "Фосфаты",
      "alkalinity": "Щелочность",
      "free_chlorine": "Свободный хлор",
      "total_chlorine": "Общий хлор",
      "pressure": "Давление фильтра"
    },
    "time": {
      "seconds": "{seconds} секунд{plural}",
      "minutes": `{minutes} минут{plural} назад`,
      "hours": `{hours} часов{plural} назад`,
      "days": `{days} дней{plural} назад`
    }

**Comment by wilsto** [comment]
added 👍 . Thanks both of you
