### ISSUE TITLE
[BUG] Sensor number does not support rounding 



### ISSUE THREAD

**Issue by cloudbr34k84** [wilsto/pool-monitor-card#3]
My temperature sensors are displaying long number for some reason 

Can we have it so it respects what is configured for the entity decimal? 

- [ ] ![Screenshot_20230521-201642.png](https://github.com/wilsto/pool-monitor-card/assets/58960644/8632ea13-81a5-412e-9680-7511f79e70b4)

**Comment by wilsto** [comment]
Fixes in 1.3.2
sensor < 10 rounded to 2 decimals
sensor < 100 rounded to 1 decimals
sensor > 100 rounded to 0 decimals
![image](https://github.com/wilsto/pool-monitor-card/assets/4889715/846b600a-3f19-4a3b-af36-1911b12f991a)

**Comment by letripeurfou** [comment]
> Just installed the Card today, bug seems to be back on Card Version Installed: 2.1.0
> 
> <img alt="Image" width="641" height="502" src="https://private-user-images.githubusercontent.com/79155054/463739644-b705418d-f352-469d-a06f-3199e89f0d4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMxMTkwMDQsIm5iZiI6MTc1MzExODcwNCwicGF0aCI6Ii83OTE1NTA1NC80NjM3Mzk2NDQtYjcwNTQxOGQtZjM1Mi00NjlkLWEwNmYtMzE5OWU4OWYwZDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIxVDE3MjUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMjM3ZDI4YjIzNGEyYWQ2MTYyODNkM2UzNDdkZDUxN2Q4MGMyNWE2YmIwOTVmMzk4NmExNjg5NGVlOTA0ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uzvl5veHmXccMWoGDC3YYF5XzDrzBMeTA6n29xaveIk"> <img alt="Image" width="775" height="435" src="https://private-user-images.githubusercontent.com/79155054/463740154-b91e6e1a-1c7b-4418-83fb-63cc427fcda0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMxMTkwMDQsIm5iZiI6MTc1MzExODcwNCwicGF0aCI6Ii83OTE1NTA1NC80NjM3NDAxNTQtYjkxZTZlMWEtMWM3Yi00NDE4LTgzZmItNjNjYzQyN2ZjZGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIxVDE3MjUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYThhZjA5MTAyNWEyYWY1NDE5NDU4YTdlODNiNWQ1ZWZiYWUzZjBhOTUwOTFjMDgwZDM5OWMzN2YwZDMwNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FJDmg2g0YkYLjuh0teFZ5o1wQi5y5nSG8xZ7Av-aR9w"> <img alt="Image" width="695" height="609" src="https://private-user-images.githubusercontent.com/79155054/463740436-a59f78ab-e78f-4a60-8fbf-87b59cbcd69a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMxMTkwMDQsIm5iZiI6MTc1MzExODcwNCwicGF0aCI6Ii83OTE1NTA1NC80NjM3NDA0MzYtYTU5Zjc4YWItZTc4Zi00YTYwLThmYmYtODdiNTljYmNkNjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIxVDE3MjUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYTYwMzhmZDY5ZWU5ZDNlODYzYjhhODcwYzk5YzdiYTAxNzQxMWE2MmU4MTIxZTM2ODRmMzBlOWI0YzYyMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9y_kHUNiVuYAriqk1QZQ5ufeCf0tIcZnkmf3tULITmc">

Same for me.
