### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by soupman98** [wilsto/pool-monitor-card#34]
I'm unable to follow the installation instructions for this. I have 2 files in \ha\ww\community\pool-monitor-card. (js and js.gz)
I created a new card from scratch but I don't get any visuals. Somewhat new to HA/GitHub. I don't understand the Lovelace instructions. Running HAOSS.

`type: custom:pool-monitor-card
title: Pool Monitor Care Title Here
compact: true
show _names: true
show_labels: true
language: en
temperature: 7138npc_air_temp
ph: sensor.your_ph_sensor
salinty: blah
free_chlorine: adf
total_chlorine: adrf
alkalinity: adsf
pressure: asdf`

**Comment by wilsto** [comment]
Hi @soupman98, can you try this ?

`type: custom:pool-monitor-card 
title: Pool Monitor Care Title Here 
compact: true 
show_names: true 
show_labels: true 
language: en 
temperature: 7138npc_air_temp 
`

**Comment by wilsto** [comment]
Hi @soupman98  I am closing this issue for now. Please feel free to reopen it if the problem persists.

**Comment by soupman98** [comment]
Just seeing this here in mail.. I'll look in G/Hub


________________________________
