### ISSUE TITLE
[FeatureRequest]Compatibilité matérielle

### ISSUE THREAD

**Issue by hlaffez** [wilsto/pool-monitor-card#36]
Bonjour,
Je vous informe que votre carte fonctionne avec le capteur piscine Tuya BLE-YL01 et permet d'afficher les 6 informations suivantes :
température, ph, orp, tds, chlore libre, salinité.
Seule la valeur Ec de conductivité électrique ne semble pas pris en compte par votre carte.
Merci pour le travail

**Comment by wilsto** [comment]
Added in readme :) Thanks
