### ISSUE TITLE
[BUG] values smaller than 3 digits are shown with a decimal and a zero or 2 to make 3 digits

### ISSUE THREAD

**Issue by mclever** [wilsto/pool-monitor-card#40]
When a sensor value is less than 100, 3 digits are always shown. For example free chlorine is 1, 1.00 is shown in the card instead of just 1 like the value is. If fc was 10, 10.0 would be displayed. If fc was 100, then 100 would be displayed.

**Expected behavior**
Values should be displayed as the value of the sensor and not have decimals added.

**Comment by wilsto** [comment]
Corrected in 1.7.0
