### ISSUE TITLE
Dual ph readings

### ISSUE THREAD

**Issue by danmrossi** [wilsto/pool-monitor-card#43]
Hi all is it possible to have a second ph reading as in ph_2? I see we can do it for temp but doesn’t seem to work for ph?

**Comment by wilsto** [comment]
Resolved in the latest Version 2.0.
https://github.com/wilsto/pool-monitor-card?tab=readme-ov-file#multiple-entities-per-sensor
![image](https://github.com/user-attachments/assets/e843198b-e48e-4749-8d4f-3fd4a80bcf30)

**Comment by danmrossi** [comment]
Thank you :)
Sent from my iPhone

On 1 Dec 2024, at 12:14 am, wilsto ***@***.***> wrote:

﻿

@danmrossi<https://github.com/danmrossi> Resolved in the latest Version 2.0.
https://github.com/wilsto/pool-monitor-card?tab=readme-ov-file#multiple-entities-per-sensor
image.png (view on web)<https://github.com/user-attachments/assets/e843198b-e48e-4749-8d4f-3fd4a80bcf30>
