### ISSUE TITLE
[FeatureRequest] Icon selection (or option for no icon)

### ISSUE THREAD

**Issue by doenau** [wilsto/pool-monitor-card#44]
The supplied icons that appear to the left of the charts do not fit with my theme.
It would be helpful to have the option to either:

- disable the icon
- use a built-in mdi: icon from home assistant.

**Comment by wilsto** [comment]
![image](https://github.com/user-attachments/assets/8e4a0414-75a3-4dfe-9afb-10b2de3e5f35)
Done in v1.9.0
