### ISSUE TITLE
[FeatureRequest] Hardware Update

### ISSUE THREAD

**Issue by cloudbr34k84** [wilsto/pool-monitor-card#5]
I just wanted to add that I have a couple of other devices that I use for monitoring pool chemicals and temperature

WiFi Tuya Smart PH Meter Data Logger Temp TDS Salinity S.G. EC ORP Water Tester Monitor Analyzer for Aquariums Pool Hydroponics
https://www.aliexpress.com/item/1005005050612094.html?spm=a2g0o.order_list.order_list_main.157.55fb1802us7mGL
![image](https://github.com/wilsto/pool-monitor-card/assets/58960644/5786bf74-5cff-4dbd-bd32-25156b4559e0)

I use this device to measure the temperature of the bottom of the pool. 
Jaalee JHT-P Temperature/Humidity/Dewpoint/VPD Sensor Indoor Meter Controller Measurement Hygrometer Wireless
https://www.aliexpress.com/item/1005002724652551.html?spm=a2g0o.order_list.order_list_main.178.55fb1802us7mGL
![image](https://github.com/wilsto/pool-monitor-card/assets/58960644/d5e44d81-36a4-49fa-8b19-520af5f11f02)

**Comment by wilsto** [comment]
Thanks @cloudbr34k84 I will add them
How do you connect to HA and retrieve values ? Do you a link to provide to people

**Comment by wilsto** [comment]
I add a new page with your suggestion
https://github.com/wilsto/pool-monitor-card/blob/master/example/hardware.md

**Comment by cloudbr34k84** [comment]
> Thanks @cloudbr34k84 I will add them How do you connect to HA and retrieve values ? Do you a link to provide to people

For the Tuya device you need to TuyaLocal
The Jaalee JHT-P uses the inbuilt Bluetooth integration

**Comment by wilsto** [comment]
readme updated. Thanks
