### ISSUE TITLE
[BUG] Sensor ec is not supported ?

### ISSUE THREAD

**Issue by jhbugues** [wilsto/pool-monitor-card#52]
**Describe the bug**
I first want to thank you very much : your work is great and useful.

Your card is working perfectly with my Tuya : [BLE-YL01](https://www.zigbee2mqtt.io/devices/BLE-YL01.html)

but one thing, about only one sensor : 
I can't add the Ec sensor.
here is what it says :
"Sensor ec is not supported. Please verify its configuration and ensure it is compatible with the card."

but in your "code page" it's allowed : 
ec 	Optional* 	The entity that measures the electrical conductivity of the water.

My HAOS, running in a miniPC is up to date.

Thanks for all

![Capture d’écran 2024-12-03 à 16 43 31](https://github.com/user-attachments/assets/aed9c6cc-d567-4055-a0d8-0a4594460c48)

**Comment by wilsto** [comment]
Hi @jhbugues, I updated the documentation ahead of the release. EC will be available in version 2.1. I will create a beta version so you can access it before the release is finalized.

**Comment by wilsto** [comment]
Done 
![image](https://github.com/user-attachments/assets/e3a99504-5a9b-4409-babc-e9957e1c1b85)

**Comment by jhbugues** [comment]
You're great. Thx !
But for me, there is no hurry. The current weather in France is not suitable for swimming

Merci beaucoup ;-)
(Mais pour moi, rien ne presse, le temps actuel en France ne se prête pas à la baignade :-))
So I'll close this topic.

**Comment by wilsto** [comment]
v2.1.0 is released

**Comment by jhbugues** [comment]
It's working fine, now. 
Thx again !
![Capture d’écran 2024-12-07 à 12 15 05](https://github.com/user-attachments/assets/1bd53e2d-4d82-441d-b743-80eb1ddfefea)
