### ISSUE TITLE
[FeatureRequest] plural should be translatable

### ISSUE THREAD

**Issue by woopstar** [wilsto/pool-monitor-card#53]
I am about to add Danish as part of the translations, but the plural key must also be translated as we are not using "s" in the ends in Danish.

**Comment by wilsto** [comment]
Hi @woopstar, thank you for your contribution. In this specific case, I recommend not including {plural} directly in the sentence within your DA translation file. Please adjust the structure to align with Danish grammatical rules

time: {
    seconds: 'gerade erst',
    minutes: 'vor {minutes} Minute{plural}',
    hours: 'vor {hours} Stunde{plural}',
    days: 'vor {days} Tag{plural}',
  },

**Comment by woopstar** [comment]
@wilsto 

Thanks for your feedback. How would you suggest then to fix the issue where plural is different. Example for hours:

1 hour:
```
time: {
    hours: '{hours} time siden',
  },
``` 
2 hours
```
time: {
    hours: '{hours} timer siden',
  },
``` 

The plural here is `r`

**Comment by wilsto** [comment]
I propose adding a new property, plural_suffix, which can be adapted per language to adjust the placement of {plural}. 
This approach allows greater flexibility for localization
What do you think?

**French**
`time: {
  plural_suffix: 's',
  hours: 'il y a {hours} heure{plural}',
},`

**Danish**
`time: {
  plural_suffix: 'r',
  hours: '{hours} timer{plural} siden',
},
`

**Comment by woopstar** [comment]
> What do you think?

I think it would work very well if it's possible to override the plural. So i +1 this one. Then you can adapt it "per language"

**Comment by wilsto** [comment]
@woopstar It will be included in version 2.1.0.

**Comment by woopstar** [comment]
There is another issue. In danish the plural differs per type. So we need to rethink it.

1 hour:
```
time: {
  seconds: 'lige nu',
  minutes: '{minutes} minut siden',
  hours: '{hours} time siden',
  days: '{days} dag siden',
},
```

Multiple hours:
```
time: {
  seconds: 'lige nu',
  minutes: '{minutes} minutter siden',
  hours: '{hours} timer siden',
  days: '{days} dage siden',
},
```

As you can see, the plural differs on minutes, hours and days. Welcome to the love of the danish language.

Would it be better to make an additional field that overrides:

```
time: {
  seconds: 'lige nu',
  minutes: '{minutes} minut siden',
  hours: '{hours} time siden',
  days: '{days} dag siden',
},
time_plural: {
  seconds: 'lige nu',
  minutes: '{minutes} minutter siden',
  hours: '{hours} timer siden',
  days: '{days} dage siden',
},
```

**Comment by wilsto** [comment]
Hi @woopstar Indeed, I understand that in some languages, conjugation isn't as simple as adding a suffix. Let's go with your proposal, which makes it possible to handle these different contexts.

**Comment by wilsto** [comment]
Done in release 2.1.0 :  https://github.com/wilsto/pool-monitor-card/releases/tag/v2.1.0
