### ISSUE TITLE
[BUG] Tap on graph does not open History

### ISSUE THREAD

**Issue by sanketgroup** [wilsto/pool-monitor-card#54]
**Describe the bug**
Previously when we tapped on a graph, it was opening Hisotury of that particular sensor. 

In new version, Tap action does not do anything

**Comment by wilsto** [comment]
Thanks @sanketgroup I will check it and add an unit testing, to prevent regression.

**Comment by wilsto** [comment]
Corrected in version 2.1.0 released soon
![image](https://github.com/user-attachments/assets/810f41d3-596a-4528-af1c-d4ad293f2f37)
