### ISSUE TITLE
[FeatureRequest] YAML code block for example cards

### ISSUE THREAD

**Issue by phrak** [wilsto/pool-monitor-card#55]
Hi Wilsto, thank you for a great add-on! 

Would you be able to provide the YAML code for your example cards please?
You do have the YAML in the PNG, but it would be very useful to have a code block in the documentation that we can copy and paste.

https://github.com/wilsto/pool-monitor-card/tree/master/example

Thanks is advance!

**Comment by wilsto** [comment]
Hi @phrak, you can already find them in "Tests" folder" : https://github.com/wilsto/pool-monitor-card/tree/master/tests/views/v2 
![image](https://github.com/user-attachments/assets/a639b3c9-f0a8-41ed-b06f-7d8558433282)
