### ISSUE TITLE
[BUG] Unable to get second temperature_2 entity to show

### ISSUE THREAD

**Issue by cloudbr34k84** [wilsto/pool-monitor-card#6]
I updated the card to 1.4.0 but i the 2nd temperature entity is not working
![image](https://github.com/wilsto/pool-monitor-card/assets/58960644/2668c7fb-576c-45c6-ac87-4664553cc3d0)

**Comment by wilsto** [comment]
Hi @cloudbr34k84, can you try to reload your lovelace UI. I tested in my production env with 1.4.0 and it works for me.
If not for you can you check your web browser console log to ee if an error occurs ?

Here my code and results.
  - type: custom:pool-monitor-card
    temperature: sensor.pool_chlorinator_filter_temperature
    temperature_2: sensor.pool_chlorinator_filter_temperature
    ph: sensor.pool_chlorinator_ph
    orp: sensor.pool_chlorinator_orp
    compact: true
    
![image](https://github.com/wilsto/pool-monitor-card/assets/4889715/1c7d96a7-835b-4677-b2b9-d62801f0e1a8)

**Comment by cloudbr34k84** [comment]
for some reason i had not added /local/community/pool-monitor-card/pool_monitor_card.js

**Comment by wilsto** [comment]
Sorry, I didn't understand your last answer, does it work now?

**Comment by cloudbr34k84** [comment]
> Sorry, I didn't understand your last answer, does it work now?

Yep all good just didn't add the dashboard resource
