### ISSUE TITLE
[BUG] Compact Mode does not have enough padding at the bottom as number go over the edge

### ISSUE THREAD

**Issue by cloudbr34k84** [wilsto/pool-monitor-card#7]
See the image below, you will notice in compact mode the numbers are over the edge of the bottom of tge card
![image](https://github.com/wilsto/pool-monitor-card/assets/58960644/8df35b7e-9647-47bf-a4c4-8683e1cc7bb8)

**Comment by wilsto** [comment]
thanks @cloudbr34k84 it's fixed in v1.5.0

![image](https://github.com/wilsto/pool-monitor-card/assets/4889715/c8b378de-3da7-4129-af67-9d4149ae7f9b)

**Comment by cloudbr34k84** [comment]
> thanks @cloudbr34k84 it's fixed in v1.5.0
> 
> ![image](https://github.com/wilsto/pool-monitor-card/assets/4889715/c8b378de-3da7-4129-af67-9d4149ae7f9b)
> 

Thank you 
Im going to be adding my new pool monitor this weekend so all the other sensors will be added
